# Generated by Django 6.0.3 on 2026-03-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
