# Generated by Django 6.0.3 on 2026-03-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_model_to_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='max_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
