# Generated by Django 6.0.3 on 2026-03-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_add_llm_usage_reembed_log'),
        ('chat', '0003_add_temperature_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to='agent.agent'),
        ),
    ]
