# Generated by Django 6.0.3 on 2026-03-19 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_add_is_default_tool_execution_heartbeat_skill'),
        ('chat', '0003_add_temperature_max_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReembedLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('paragraph_count', models.IntegerField()),
                ('records_added', models.IntegerField(default=0)),
                ('records_deleted', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(default='auto', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('source', models.CharField(default='unknown', max_length=20)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='chat.conversation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='agent.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='agent_llmus_created_aad98d_idx'), models.Index(fields=['source', 'created_at'], name='agent_llmus_source_538de3_idx')],
            },
        ),
    ]
