# Generated by Django 6.0.3 on 2026-03-20 12:14

import agent.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_add_llm_usage_reembed_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPServer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('transport', models.CharField(choices=[('stdio', 'stdio (local process)'), ('sse', 'SSE (remote HTTP)')], max_length=10)),
                ('command', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('env', agent.models.EncryptedJSONField(blank=True, default=dict)),
                ('auto_approve_tools', models.JSONField(default=list)),
                ('auto_approve_resources', models.BooleanField(default=False)),
                ('always_include_resources', models.JSONField(default=list)),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='unknown', max_length=20)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
