# Generated by Django 6.0.3 on 2026-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_add_mcp_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='always_include_resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mcpserver',
            name='auto_approve_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
