# Generated by Django 6.0.3 on 2026-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_fix_mcpserver_blank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='triggered_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
