# Generated by Django 6.0.3 on 2026-03-22 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_add_triggered_skills'),
        ('chat', '0004_add_active_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='workflow_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='workflow_step_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='trigger_source',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('cli', 'CLI'), ('heartbeat', 'Heartbeat'), ('workflow', 'Workflow')], max_length=20),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('definition', models.JSONField()),
                ('filename', models.CharField(max_length=255)),
                ('delivery', models.CharField(default='announce', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('celery_beat_id', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='agent.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='chat.conversation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agentrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='agent.workflow'),
        ),
    ]
