# Generated by Django 6.0.3 on 2026-03-23 07:13

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_seed_default_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='skill_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
