# Generated by Django 6.0.3 on 2026-03-25 00:57

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_add_skill_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('upload', 'File Upload'), ('url', 'Web URL'), ('text', 'Pasted Text')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('raw_content', models.TextField(help_text='Original full text')),
                ('metadata', models.JSONField(default=dict)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('chunk_index', models.PositiveIntegerField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agent.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='docchunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
