# Generated by Django 6.0.3 on 2026-04-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_add_knowledge_document_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolexecution',
            name='is_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='parallel_group',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
