# Generated by Django 6.0.3 on 2026-04-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_add_approval_reason_round_to_tool_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedSkillSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(help_text='Resolved absolute path to the trusted skill source directory.', max_length=500, unique=True)),
                ('approved_by', models.CharField(blank=True, help_text='Username or "system" for auto-approved entries.', max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='source_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
