# Generated by Django 6.0.3 on 2026-04-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_add_trustedskillsource_and_skill_source_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='health_probe_tool',
            field=models.CharField(blank=True, help_text='Tool name with no required parameters used to probe session health (e.g. get_current_date). Used together with session_dead_error_codes.', max_length=100),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='session_dead_error_codes',
            field=models.JSONField(blank=True, default=list, help_text='JSON-RPC error codes that indicate server-side session expiry (e.g. [-32602]). Leave empty if the server uses transport-level disconnect errors only.'),
        ),
    ]
